modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Raaadish/Mythscapes/issues"
license="MIT"


[[mods]]
    modId="mythscapes"
    version="${file.jarVersion}"
    displayName="Mythscapes"
    credits="The Mythscapes team"
    authors="Radish"
    description="Mythical stuff"

[[dependencies.mythscapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    side="BOTH"

[[dependencies.mythscapes]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    side="BOTH"
